### ISSUE TITLE
Upgrade `protobuf` dependency

### ISSUE THREAD

**Issue by arturpat** [confident-ai/deepeval#373]
[This PR](https://github.com/confident-ai/deepeval/pull/322) upgrades `protobuf` to version 4.x but it seems that the main branch still references 3.x. Could we get `protobuf` upgraded to version 4 on main?

**Comment by ji21** [comment]
Hey @arturpat, it was later downgraded because one of our metrics depend on that version. But don’t worry, that metric is getting deprecated tomorrow, I will be able to upgrade it in tomorrow’s release.

Do you have discord by the way? Please join us to since we find it easier to communicate there: https://discord.gg/a3K9c8GRGt

**Comment by arturpat** [comment]
Awesome, thank you! I do have discord but I'm not using it that actively. I'll make sure to join and check it out from time to time.

**Comment by penguine-ip** [comment]
@arturpat the latest version uses x4.! Upgrade to 0.20.42 :)
