### ISSUE TITLE
`Scorer.answer_relevancy_score` fails due to import of classes not exposed in models init

### ISSUE THREAD

**Issue by ymzayek** [confident-ai/deepeval#474]
**Describe the bug**
The relevant classes are commented out in the `deepeval.models.__init__` which breaks the Scorer API for some methods. This may be due to coming changes to the API but there should probably be a warning or better documentation of `Scorer`

**To Reproduce**

```python
from deepeval.scorer import Scorer

actual_output = "My name is John."
input="What is your name?"
print(Scorer.answer_relevancy_score(predictions=actual_output, target=input))
```
```bash
UnboundLocalError: cannot access local variable 'CrossEncoderAnswerRelevancyModel' where it is not associated with a value
```

**Desktop (please complete the following information):**
 - OS: Debian 12

**Comment by penguine-ip** [comment]
Currently Scorer is for internal use, and supporting it with more docs for users to plug and use will come later this month. The error is likely due to a delayed import, basically we don't want to bulk up deepeval's package size by installing more than necessary packages (since Scorer.answer_relevancy_score) is no longer used (although it still works, we found a better alternative)

**Comment by ymzayek** [comment]
Ok makes sense, thx! Feel free to close this issue
