### ISSUE TITLE
Custom dataset evaluation giving  ValueError: Input, actual output, and retrieval context cannot be None

### ISSUE THREAD

**Issue by piseabhijeet** [confident-ai/deepeval#568]
When I create an evaluation dataset using EvaluationDataset and I use it with LLMTestCase, I get this:

```
  File "/Users/abhijeet.pise/miniconda3/envs/evaluation/lib/python3.12/site-packages/deepeval/evaluate.py", line 174, in evaluate
    test_results = execute_test(test_cases, metrics, True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abhijeet.pise/miniconda3/envs/evaluation/lib/python3.12/site-packages/deepeval/evaluate.py", line 76, in execute_test
    metric.measure(test_case)
  File "/Users/abhijeet.pise/miniconda3/envs/evaluation/lib/python3.12/site-packages/deepeval/metrics/faithfulness/faithfulness.py", line 43, in measure
    raise ValueError(
ValueError: Input, actual output, and retrieval context cannot be None
```

I am sure my dataset has all Input, actual output, and retrieval context values..

**Comment by piseabhijeet** [comment]
Hi @penguine-ip 

Actually I tried running the same for two metrics - correctness and hallucination - it works perfectly.. but when I try to include all the other metrics like faithfulness, contextual similarity, it fails. this is weird..

if it was a missing value issue, the two metrics wouldn't have run successfully.

**Comment by penguine-ip** [comment]
Oh i see, correctness and hallcuination does not require `retrieval_context` but other metrics you mentioned does.

I assume you only provided `context` but not `retrieval_context`. Are you building something RAG? if you are, don't use hallucination and switch to faithfulness altogether.

**Comment by piseabhijeet** [comment]
I see, got your point! Thanks for the quick response. 

Also if a dataset is created inside a module and metrics are passed as list, do we explicitly specify number of workers? if yes, where do I set it?

I see '-n' as parameter on command line but was wondering if a similar parameter is there inside dataset.evaluate module.

**Comment by piseabhijeet** [comment]
Where are evaluation results stored? I see a temporary json file in the same folder but its not getting updated when running bulk eval.

**Comment by penguine-ip** [comment]
@piseabhijeet You should be able to store results locally using this instruction: https://docs.confident-ai.com/docs/getting-started#create-your-first-test-case

Let me know if it doesn't work. There's always the option to login to Confident AI too with this one liner in the CLI: `deepeval login`

You can also do it in python code: https://docs.confident-ai.com/docs/confident-ai-introduction (scroll to bottom)

Not yet, right now we execute each test case individually, and then for each test case execute each metric individually (so like a double for loop)

We're going to be releasing a big update tomorrow that allows you to run metrics concurrently on a test case, (so a single for loop)

You don't have to specify workers for this, we'll handle everything under the hood with coroutines. If you are using a custom model (eg., https://docs.confident-ai.com/docs/metrics-introduction#using-a-custom-llm), let me know because I'll need to help you support async execution.

The -n flag in deepeval test run allows you to run multiple test cases at once using multiple processes in parallel. We're not supporting multiprocessing for the evaluate function for now.

**Comment by penguine-ip** [comment]
@piseabhijeet also come join our discord, there will be major updates over the weekend and any breaking changes will be updated there: https://discord.com/invite/a3K9c8GRGt

**Comment by piseabhijeet** [comment]
thanks for the prompt response @penguine-ip !

**Comment by penguine-ip** [comment]
hey @piseabhijeet, updates on discord, but in short evaluate function now runs all metrics concurrently for each test case: https://docs.confident-ai.com/docs/evaluation-test-cases#evaluate-test-cases-in-bulk

It's a big changes so please let me know if you catch any bugs!

**Comment by piseabhijeet** [comment]
This is amazing! Looking forward to try it this week!

**Comment by piseabhijeet** [comment]
Also I notice that some of the test cases are missing in the .json file output and the code never stops executing. Last terminal output:
<img width="623" alt="Screenshot 2024-03-10 at 15 44 22" src="https://github.com/confident-ai/deepeval/assets/57705684/e7ca9f2d-f1e1-4b0e-a5ba-e0689486bb93">

**Comment by penguine-ip** [comment]
Hey! I’ve limited web access right now but I have discord available, do you
mind copy and pasting it there so I can help out asap? (Can’t view the code
and photo)
