### ISSUE TITLE
Knowledge Retention metric discrepancy

### ISSUE THREAD

**Issue by AnanyaRaval** [confident-ai/deepeval#737]
**Describe the bug**
1. The docs for [Knowledge Retention Metric](https://docs.confident-ai.com/docs/metrics-knowledge-retention) specify that in strict mode, the threshold is set to `0`. However, in the [code](https://github.com/confident-ai/deepeval/blob/main/deepeval/metrics/knowledge_retention/knowledge_retention.py#L37) the threshold is set to `1` . What is the expected correct behavior?

```python
class KnowledgeRetentionMetric(BaseConversationalMetric):
    def __init__(
        self,
        threshold: float = 0.5,
: 
: 
self.threshold = 1 if strict_mode else threshold
```

2. According to the [Knowledge Retention template](https://github.com/confident-ai/deepeval/blob/main/deepeval/metrics/knowledge_retention/template.py), the verdict is `yes` if LLM remembers knowledge in response, else it is a `no`. It mentions that a higher score is better, which makes sense. However, while calculating the score, it calculates the number of `no` verdicts, implying that it calculates the knowledge forgotten.  This seems incorrect to me. Shouldn't it calculate the number of `yes` verdicts or things remembered? 

**To Reproduce**
None

**Expected behavior**
None

**Screenshots**
None

**Desktop (please complete the following information):**
 Note required.

**Smartphone (please complete the following information):**
 Not required.

**Additional context**

**Comment by AnanyaRaval** [comment]
Happy to contribute changes to the library/documentation.

**Comment by penguine-ip** [comment]
Hey @AnanyaRaval, thanks for catching the error!  Indeed there is a mistake, the correct version should be 1 for a perfect score, and 0 if not for strict mode. For the docs, the equation at the bottom should be "without" instead of "with" knowledge attritions. 

The code the calculate the score is correct since we answer "no" when there is no attritions / forgetfulness. 

Would be grateful to have yo u help fix the docs and the code for the threshold! Thank you so much 😊

**Comment by AnanyaRaval** [comment]
Thanks @penguine-ip ! I have made changes you suggested in the doc. 

What code changes are required if the score calculation is accurate?
