### ISSUE TITLE
Unable to disable telemetry

### ISSUE THREAD

**Issue by ecatkins** [confident-ai/deepeval#757]
**Describe the bug**
Unable to disable telemetry feature

**To Reproduce**
- Using `os.environ['DEEPEVAL_TELEMETRY_OPT_OUT'] = "YES"` at the top of my script
- Running `deepeval test run test_xx.py` over test cases 

**Expected behavior**
- I would expect any telemetry behavior to be disabled. Instead I am still seeing attempted connections (which my system is blocking), see screenshot below

**Screenshots**
<img width="1045" alt="image" src="https://github.com/confident-ai/deepeval/assets/8319226/25a872d9-a96d-4e48-937e-27f098fbb70a">

**Comment by penguine-ip** [comment]
hey @ecatkins, can you quickly print the env variable to see if it is indeed "YES" and resolves to true?

**Comment by penguine-ip** [comment]
@ecatkins I'm assuming this is no longer an issue?

**Comment by noa-weiss** [comment]
Was this ever fixed? I'm having the same problem.

**Comment by Jarzab3kDH** [comment]
+1 , when I set env variable to "YES" I get:

  File "/home/vscode/.local/lib/python3.12/site-packages/deepeval/telemetry.py", line 235, in capture_metric_type
    posthog.capture(distinct_id=distinct_id, event=event, properties=properties)
    ^^^^^^^
NameError: name 'posthog' is not defined. Did you mean: 'Posthog'?

which is probably unrelated error, but the issue is that the this code gets executed, which imo shouldn't be the case.

Kind feedback - this is a "no-go" from my company perspective and destroys trust at very beginning.

The other thing is that you have stored API keys in git repository, which is another "no-go" for us as we cannot trust how you treat other sensitive information.

Again this is just kind feedback, as I spent couple of days testing it hoping I can use it in my project :-)

**Comment by satyaprakash1729** [comment]
@penguine-ip We're using `3.0.8`. We're still seeing the issue.

**Comment by penguine-ip** [comment]
@satyaprakash1729 can you paste in the error message? Thanks

**Comment by satyaprakash1729** [comment]
Hi, looks like this is resolved in 3.1.0. I'll give it a try and update this thread. Thank you!

**Comment by mykolas-nice** [comment]
With 3.5.2 I have an issue. 

I either get error uploading: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ when telemetry is enabled. 

When I try to disable, I get "Error: name 'posthog' is not defined". The env is set to export DEEPEVAL_TELEMETRY_OPT_OUT=1
export DEEPEVAL_TELEMETRY_OPT_OUT=YES does not work. 

Setting os.environ['DEEPEVAL_TELEMETRY_OPT_OUT'] = "YES" on the top of the script does not help either. I get the https error.

**Comment by penguine-ip** [comment]
Hey @mykolas-nice , from `3.5.0` onwards we've standardized all the env variables to boolean `0` or `1` flags, you can see the latest in our docs here: https://deepeval.com/docs/data-privacy

Let me know if this helps

**Comment by mykolas-nice** [comment]
Hey, @penguine-ip, thanks for the reply.

I've tried to set DEEPEVAL_TELEMETRY_OPT_OUT=1, and after this during metrics evaluation I get the error: Error: name 'posthog' is not defined

**Comment by mykolas-nice** [comment]
Tried version 3.4.0 - and found no issues. No errors appeared in simple execution, nor with DEEPEVAL_TELEMETRY_OPT_OUT set to YES or 1.
