### ISSUE TITLE
Why actual_output is required for Context Relevancy?

### ISSUE THREAD

**Issue by isaactl** [confident-ai/deepeval#924]
hi, thanks for building this great tool. i have been using this tool for a while, and found **actual_output** is actually not used by Contextual Relevancy metric, but the design is(from [docs](https://docs.confident-ai.com/docs/evaluation-test-cases)) **actual_output** is always needed.

**Comment by penguine-ip** [comment]
@isaactl Thanks! Intentional since evaluation is owned by an LLMTestCase, which by default requires input and actual output regardless of whether they are used in evaluation. (wanted to make this a strictly LLM evaluation framework rather than any NLP evaluation task)

If you really don't want to provide an actual output, simply provide an empty string and it won't affect anything.
